import dotenv from 'dotenv';
dotenv.config({ path: 'c:/PROJECTS/CareerIQ/backend/.env' });
import mongoose from 'mongoose';
import { db } from './src/db';
import { processOnboardingJob } from './src/services/worker';
import { setUseMockMongo } from './src/db/mongoService';

async function main() {
  await mongoose.connect(process.env.MONGO_URI || '');
  console.log('Connected to MongoDB');

  // Find all student profiles
  const profiles = await mongoose.connection.collection('localstudentprofiles').find().toArray();
  console.log(`Found ${profiles.length} student profiles to process.`);

  setUseMockMongo(false);

  for (const p of profiles) {
    console.log(`\n--------------------------------------------`);
    console.log(`Processing onboarding for User: ${p.fullName} (ID: ${p._id})`);
    console.log(`GitHub URL: ${p.githubUrl}`);
    console.log(`Resume URL: ${p.resumeUrl}`);

    if (!p.githubUrl) {
      console.log('Skipping because profile has no GitHub URL.');
      continue;
    }

    if (!p.resumeUrl) {
      console.log('No resumeUrl. Setting onboardingCompleted = true directly so they can access dashboard.');
      await db.updateStudentOnboardingFields(p._id as any as number, {
        onboardingCompleted: true,
        profileAutoGenerated: true
      });
      continue;
    }

    const jobId = new mongoose.Types.ObjectId().toString();
    // Create job tracker
    const job = new (mongoose.models.Job || mongoose.model('Job', new mongoose.Schema({})))({
      _id: new mongoose.Types.ObjectId(jobId),
      githubUrl: p.githubUrl,
      status: 'pending',
    });
    await job.save();

    try {
      await processOnboardingJob(
        jobId,
        p.userId as any as number,
        p.resumeUrl,
        p.githubUrl,
        p.targetRole || 'Frontend Engineer'
      );
      console.log(`Onboarding job finished successfully for user ID ${p.userId}!`);
    } catch (err: any) {
      console.error(`Onboarding job failed for user ID ${p.userId}:`, err);
    }
  }

  await mongoose.disconnect();
  console.log('\nAll profiles processed successfully!');
}

main().catch(console.error);
